<?php

function hello_init(){

}

function hello_menu(){
    $items = array();

    $items['hellopage'] = array(
        'title' => 'My hello page',
        'description' => 'Hello user',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('hello_showHelloForm'),
        'access callback' => 'user_access',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM
    );

    $items['gethello'] = array(
        'page callback' => 'hello_AjaxCall',
        'access callback' => 'user_access',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK
    );

    $items['console/restful/template'] = array(
        'page callback' => 'hello_TemplateCall',
        'page arguments' => array(2),
        'access callback' => 'user_access',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK
    );

    return $items;
}

function hello_TemplateCall() {
    $args = func_get_args();
    array_shift($args);
    $templateFile = path_to_theme() . '/templates/' . implode('/', $args) . '.tpl.php';
    $html = theme_render_template($templateFile, array());
    print $html;

}

function hello_AjaxCall() {
    echo 'Hello '.$_GET['name'].' !';
}

function hello_showHelloForm() {
    $form = array();

    $form['name'] = array(
        '#type' => 'textfield',
        '#title' => 'Enter your name'
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Submit'
    );

    $form['#submit'][] = 'hello_showHelloForm_submit';

    $form['#suffix'] = '<input type="button" id="btnAjax" value="Submit with Ajax" /><br/>
    <div id="msg-display"></div><br/>
    <input type="button" id="btnCallTemplate" value="Call template with Ajax" />';

    drupal_add_js(drupal_get_path('module', 'hello').'/hello.js');

    return $form;
}

function hello_showHelloForm_submit($form, &$form_state){
    if($form_state['values']['name'] == ''){
        form_set_error('name', 'Name can not be empty');
    } else {
        drupal_set_message('Hello  '.$form_state['values']['name'].' !');
    }

}

?>